# Generated by Django 5.1.6 on 2025-02-14 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='bottles_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertable',
            name='referral_code',
            field=models.CharField(default='BE822B', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
