# Generated by Django 5.1.6 on 2025-02-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='referral_code',
        ),
    ]
