# Generated by Django 5.1.6 on 2025-02-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location_description", models.TextField()),
                ("location", models.TextField()),
                ("points_reward", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="Challenge",
        ),
    ]
