# Generated by Django 5.1.6 on 2025-02-06 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoTitle', models.CharField(max_length=200)),
                ('videoThumbnailURL', models.CharField(max_length=200)),
                ('videoLink', models.CharField(max_length=200)),
                ('videoPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VideoWatchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchTime', models.DateTimeField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envapp.videos')),
            ],
        ),
    ]
