# Generated by Django 5.1.6 on 2025-02-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_usertable_bottles_saved_usertable_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='referral_code',
            field=models.CharField(default='CDBEB2', max_length=10, unique=True),
        ),
    ]
