# Generated by Django 5.1.6 on 2025-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_alter_usertable_options_alter_usertable_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
