# Generated by Django 5.1.6 on 2025-02-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_remove_usertable_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
