# Generated by Django 5.1.6 on 2025-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_waterstation_is_working_waterstation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterstation',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
