# Generated by Django 5.1.6 on 2025-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envapp", "0003_usertable_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="StationUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("waterStationID", models.IntegerField()),
                ("fillTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="waterstation",
            name="location",
        ),
        migrations.AddField(
            model_name="waterstation",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="waterstation",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
