# Generated by Django 5.1.6 on 2025-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0004_alter_usertable_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
