# Generated by Django 5.1.6 on 2025-02-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0004_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
