# Generated by Django 5.1.6 on 2025-02-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0005_alter_usertable_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='bottles_saved',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='referred_by',
        ),
    ]
