# Generated by Django 5.1.6 on 2025-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationToChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterStationID', models.IntegerField()),
                ('challengeID', models.IntegerField()),
            ],
        ),
    ]
