# Generated by Django 5.1.6 on 2025-03-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterstation',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='waterstation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='water_station_photos/'),
        ),
    ]
