# Generated by Django 5.1.6 on 2025-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0002_stationtochallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeClaims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('challengeID', models.IntegerField()),
            ],
        ),
    ]
